name: Create and publish a Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        timeout-minutes: 10
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:latest,${{ secrets.REGISTRY_URL }}/${{ github.repository }}:${{ github.ref_name }}
